"""Add duplicate_count and is_priority_overridden

Revision ID: 04a413ca8e76
Revises: ab30d5bb4ccd
Create Date: 2026-08-13 19:21:39.555127+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a413ca8e76'
down_revision: Union[str, None] = 'ab30d5bb4ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis', sa.Column('is_priority_overridden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('petitions', sa.Column('duplicate_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petitions', 'duplicate_count')
    op.drop_column('ai_analysis', 'is_priority_overridden')
    # ### end Alembic commands ###
