"""Add latitude and longitude to petitions

Revision ID: 12ea3f09fc2b
Revises: 001
Create Date: 2026-07-26 09:59:57.081505+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ea3f09fc2b'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_petition_history_petition_id', table_name='petition_history')
    op.add_column('petitions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('petitions', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_index('ix_petitions_department_id', table_name='petitions')
    op.drop_index('ix_petitions_status', table_name='petitions')
    op.drop_index('ix_petitions_submitted_by', table_name='petitions')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_petitions_submitted_by', 'petitions', ['submitted_by'], unique=False)
    op.create_index('ix_petitions_status', 'petitions', ['status'], unique=False)
    op.create_index('ix_petitions_department_id', 'petitions', ['department_id'], unique=False)
    op.drop_column('petitions', 'longitude')
    op.drop_column('petitions', 'latitude')
    op.create_index('ix_petition_history_petition_id', 'petition_history', ['petition_id'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###
