"""Add preferences to user

Revision ID: 15df01042468
Revises: d2e3f4a5b6c7
Create Date: 2026-08-05 10:46:19.042882+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15df01042468'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""Add preferences to user

Revision ID: 15df01042468
Revises: d2e3f4a5b6c7
Create Date: 2026-08-05 10:46:19.042882+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15df01042468'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'department_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint('uq_departments_code', 'departments', type_='unique')
    op.create_index(op.f('ix_departments_department_code'), 'departments', ['department_code'], unique=True)
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{"language": "en", "voice_input": true, "high_contrast": false, "font_size": "medium"}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_index(op.f('ix_departments_department_code'), table_name='departments')
    op.create_unique_constraint('uq_departments_code', 'departments', ['department_code'])
    op.alter_column('departments', 'department_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
