"""rename model_used to llm_model

Revision ID: 24c4f0c75b03
Revises: 0003_chat_tables
Create Date: 2026-08-02 13:25:59.563201+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c4f0c75b03'
down_revision: Union[str, None] = '0003_chat_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.drop_column('chat_messages', 'model_used')
    op.drop_index('ix_chat_sessions_last_active', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_user_id', table_name='chat_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_last_active', 'chat_sessions', ['last_active_at'], unique=False)
    op.add_column('chat_messages', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.drop_column('chat_messages', 'llm_model')
    # ### end Alembic commands ###
