"""Add location verification fields

Revision ID: 7163b1c7dc46
Revises: b2e510751aeb
Create Date: 2026-08-13 20:10:47.119375+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7163b1c7dc46'
down_revision: Union[str, None] = 'b2e510751aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petitions', sa.Column('device_latitude', sa.Float(), nullable=True))
    op.add_column('petitions', sa.Column('device_longitude', sa.Float(), nullable=True))
    op.add_column('petitions', sa.Column('device_accuracy', sa.Float(), nullable=True))
    op.add_column('petitions', sa.Column('location_verification_status', sa.String(), server_default='unverified', nullable=False))
    op.add_column('petitions', sa.Column('location_verification_reason', sa.Text(), nullable=True))
    op.add_column('petitions', sa.Column('location_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petitions', 'location_verified_at')
    op.drop_column('petitions', 'location_verification_reason')
    op.drop_column('petitions', 'location_verification_status')
    op.drop_column('petitions', 'device_accuracy')
    op.drop_column('petitions', 'device_longitude')
    op.drop_column('petitions', 'device_latitude')
    # ### end Alembic commands ###
