"""Add citizen department and match to petition

Revision ID: ab30d5bb4ccd
Revises: e665c7a006d5
Create Date: 2026-08-13 17:25:46.575103+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab30d5bb4ccd'
down_revision: Union[str, None] = 'e665c7a006d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petitions', sa.Column('citizen_department_id', sa.UUID(), nullable=True))
    op.add_column('petitions', sa.Column('department_match', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'petitions', 'departments', ['citizen_department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'petitions', type_='foreignkey')
    op.drop_column('petitions', 'department_match')
    op.drop_column('petitions', 'citizen_department_id')
    # ### end Alembic commands ###
