"""add department_code

Revision ID: ab6b65f84608
Revises: 24c4f0c75b03
Create Date: 2026-08-02 19:18:14.096928+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6b65f84608'
down_revision: Union[str, None] = '24c4f0c75b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'department_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index('ix_departments_code', table_name='departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_departments_code', 'departments', ['department_code'], unique=False)
    op.alter_column('departments', 'department_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
