"""Add translation_cache table

Revision ID: b2e510751aeb
Revises: 04a413ca8e76
Create Date: 2026-08-13 19:54:04.326689+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e510751aeb'
down_revision: Union[str, None] = '04a413ca8e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', 'target_lang', name='uq_translation_hash_lang')
    )
    op.create_index(op.f('ix_translation_cache_source_hash'), 'translation_cache', ['source_hash'], unique=False)
    op.create_index(op.f('ix_translation_cache_target_lang'), 'translation_cache', ['target_lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_cache_target_lang'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_source_hash'), table_name='translation_cache')
    op.drop_table('translation_cache')
    # ### end Alembic commands ###
