"""add_location_integrity_fields

Revision ID: e665c7a006d5
Revises: 0ed808a65118
Create Date: 2026-08-13 14:59:07.535990+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e665c7a006d5'
down_revision: Union[str, None] = '0ed808a65118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petitions', sa.Column('location_status', sa.String(), server_default='unverified', nullable=False))
    op.add_column('petitions', sa.Column('location_source', sa.String(), server_default='manual', nullable=False))
    op.add_column('petitions', sa.Column('location_accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petitions', 'location_accuracy')
    op.drop_column('petitions', 'location_source')
    op.drop_column('petitions', 'location_status')
    # ### end Alembic commands ###
